config/routes.rb
Rails.application.routes.draw do
  
  resources :events,  only: [:index, :show, :create, :destroy]
  get 'static_pages/home'
  get 'sessions/new'
  resources :users
  get "/signup", to: "users#new"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/home', to: 'static_pages#home'
  root 'static_pages#home'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, foreign_key: "user_id", class_name: "User"
    has_many :event_attendances, foreign_key: "attended_event", class_name: "EventAttendance"
    has_many :attendees, through: :event_attendances, source: :attendant
    validates :event_title,  presence: true, length: { minimum: 5 }
    validates :date,  presence: true

    scope :past, -> { where("date < ?", DateTime.now) }
    scope :future, -> { where("date > ?", DateTime.now) }

end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
    belongs_to :attendant, foreign_key: "attendee", class_name: "User"
    belongs_to :event, foreign_key: "attended_event", class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
    validates :name,  presence: true, length: { minimum: 2 }
    has_many :events, dependent: :destroy
    has_many :event_attendances, foreign_key: "attendee", class_name: "EventAttendance"
    has_many :events_attended, through: :event_attendances, source: :event


    def upcoming_events
        @future = []
        if self.events_attended.any?
          self.events_attended.each do |ev|
            @future << ev if ev.date > Time.now
          end
        end
        @future
    end
    
    def past_events
        @past = []
        if self.events_attended.any?
          self.events_attended.each do |ev|
            @past << ev if ev.date <= Time.now
          end
        end
        @past
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    private
    # Confirms a logged-in user.
    def logged_in_user
     unless logged_in?
       flash[:danger] = "Please log in."
       redirect_to login_url
     end
   end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  def index
    @ev_future = Event.future
    @ev_past = Event.past
  end

  def create
    @event = current_user.events.build(events_params)
    if @event.save
      current_user.events_attended << @event
      if attendancy_params != [0]
        attendancy_params[0..-2].each{|user| 
        EventAttendance.create(attendee: user.to_i, attended_event: @event.id )}
      end
      flash[:success] = "Event created!"
      redirect_to @event
    else
        flash[:danger] = "Please fill Both title and date"
        redirect_to root_url
    end
  end

  def show
    @event= Event.find(params[:id])
  end

  def events_params
    params.require(:event).permit(:event_title, :date)
  end

  def attendancy_params
    params.require(:attendees)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
      if user
        log_in user
        redirect_to user
      else
        flash[:warning] = "User not found. Please Signup"
        redirect_to signup_path
      end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @event  = current_user.events.build
      #@feed_items = current_user.feed.paginate(page: params[:page])
      @users = User.where.not(id: @current_user.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.upcoming_events
    @past_events = @user.past_events
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Please add your name"
      render 'sessions/new'
    end
  end
  private

  def user_params
    params.require(:user).permit(:name)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
    include SessionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if user_id = session[:user_id]
            @current_user ||= User.find_by(id: user_id)
        end
    end

    def current_user?(user)
        user == current_user
    end

    def logged_in?
      !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
   
end

app/views/events/index.html.erb
<h2> Future Events </h2>
<% @ev_future.each do |ev| %>
    <h4><%= "Event #{ev.event_title} will occur at #{ev.date}" %> 
    <%= link_to "Show Event!", event_path(ev.id) %> </h4>
<% end %>

<h2> Past Events </h2>
<% @ev_past.each do |ev| %>
    <h4><%= "Event #{ev.event_title} occured at #{ev.date}" %> 
    <%= link_to "Show Event!", event_path(ev.id) %> </h4>
<% end %>

app/views/events/show.html.erb
<h3><%= "Event #{@event.event_title} will occur at #{@event.date}" %> </h3>
<h5><%="Created by #{@event.creator.name}"%></h5>
<h2>People who are attending: </h2>
<ul>
<% @event.attendees.each do |att|%>
    <li><%= att.name %></li>
    <% end %>
</ul>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <%= link_to "Private Events", root_path %>
    <% if logged_in? %>
      <% name = current_user.name %>
      <%= link_to "#{name}", user_path(User.find(current_user.id)) %>
      <%= link_to "Log out", logout_path, method: :delete %>
    
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Events", events_path %></li>
      </ul>
      <%else%>
      <li><%= link_to "Sign Up", signup_path %></li>
      <li><%= link_to "Log In", login_path %></li>
    
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Events", events_path %></li>
      </ul>
      <%end%>
    </nav>
  </div>
</header>
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<% if logged_in? %>
  <%= form_for(@event) do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>

    <%= f.label :event_title %>
    <%= f.text_field :event_title %>

    <%= f.label :date %>
    <%= f.date_field :date %>

    <%= f.submit "Create", class: "btn btn-primary" %>

    <div class="right_box" style="width:40%;">
    <%= f.label 'invite attendees' %>
    <% @users.each do |user| %>
      <div id="row">
          <%= check_box_tag 'attendees[]', user.id %>
          <h5 style="display: inline"><%= user.name %></h5>
      </div>
    <% end %>
    <%= hidden_field_tag 'attendees[]', '0' %>
  </div>

  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>
<h3> The Events Created By <%="#{@user.name}"%> </h3>
<ul>
<% @user.events.each do |ev| %>
 <li> <%= "#{ev.event_title} at #{ev.date}" %></li>
 <% end %>
 </ul>
 <h3> <%="#{@user.name.upcase}"%> is Invited To Theese Events: </h3>
 <ul>
 <h4> Upcoming Events </h4>
 <% @upcoming_events.each do |ev| %>
    <li> <%= "#{ev.event_title} will occur at #{ev.date}" %></li>
<% end %>
</ul>

<ul>
 <h4> Past Events </h4>
 <% @past_events.each do |ev| %>
    <li> <%= "#{ev.event_title} occured at #{ev.date}" %></li>
<% end %>
</ul>